# theme = "adams_theme"
# theme = "adams_theme_minimal"
# theme = "gruvbox"
# theme = "gruvbox_dark_hard"
# theme = "adams_gruvbox"
# theme = "base16_terminal"
# theme = "base16_default_dark"
theme = "kanagawa-dragon"
# theme = "adams_rose_pine"

[editor]
scrolloff = 20
mouse = false
line-number = "relative"
cursorline = true
auto-completion = true
auto-format = false
preview-completion-insert = true
auto-info = true
true-color = true
bufferline = "always"
color-modes = true
popup-border = "all"
indent-heuristic = "hybrid"
end-of-line-diagnostics = "hint"
completion-timeout = 5
idle-timeout = 5
rulers = [110]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.statusline]
left = [
  "spacer", 
  "spacer",
  "mode", 
  "spacer", 
  "spinner", 
  "spacer", 
  "position", 
  "separator", 
  "total-line-numbers"
]
center = [
  "read-only-indicator", 
  "spacer",
  "separator", 
  "file-name", 
  "separator", 
  "spacer",
  "file-modification-indicator"
]
right = [
  "diagnostics", 
  "spacer", 
  "version-control", 
  "file-encoding", 
  "file-type", 
  "register", 
  "spacer"
]
separator = " "
mode.normal = ". normal ."
mode.insert = "+ insert +"
mode.select = "= visual ="

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints = false
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.auto-save]
focus-lost = false
after-delay.enable = false
after-delay.timeout = 6000

[editor.whitespace]
render.newline = "all"
render.tab = "all" 
characters.newline = "`"

[editor.indent-guides]
render = true
character = "."

[editor.soft-wrap]
enable = true

[editor.smart-tab]
enable = false

[keys.normal]
"ret" = "goto_word"

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"
O = ":cd C:/Users/Adam/Desktop/projects"
H = ":toggle lsp.display-inlay-hints"
h = ":toggle end-of-line-diagnostics hint error"
N = ":bc"

[keys.normal.z]
u = ":reflow"
i = ":sh cargo run > output.txt"

[keys.select]
V = "extend_to_line_bounds"

[keys.insert]
"C-backspace" = "delete_word_backward"

[editor.file-picker]
hidden = true
