# Everforest (Dark Medium)
# Authors: CptPotato, basbebe
#     Modifying author: adam-biggs

# Original Author:
# URL: https://github.com/sainnhe/everforest
# Filename: colors/everforest.vim
# Author: sainnhe
# Email: sainnhe@gmail.com
# License: MIT License

"type" = "yellow"
"constant" = "fg"
"constant.builtin" = { fg = "constant", modifiers = ["italic"] }
"constant.builtin.boolean" = "constant"
"constant.numeric" = "constant"
"constant.character.escape" = "green"
"string" = "fg"
"string.regexp" = "green"
"string.special" = "yellow"
"comment" = { fg = "grey1", modifiers = ["italic"] }
# "variable" = "fg"
"variable" = "fg"
"variable.builtin" = { fg = "constant", modifiers = ["italic"] }
"variable.parameter" = "fg"
"variable.other.member" = "fg"
"label" = "orange"
"punctuation" = "grey2"
"punctuation.delimiter" = "grey1"
"punctuation.bracket" = "fg"
"punctuation.special" = "blue"
"keyword" = "red"
"keyword.operator" = "orange"
"keyword.directive" = "constant"
"keyword.storage" = "red"
"operator" = "orange"
"function" = "green"
"function.macro" = "green"
"tag" = "orange"
"namespace" = { fg = "yellow", modifiers = ["italic"] }
"attribute" = { fg = "constant", modifiers = ["italic"] }
"constructor" = "fg"
"module" = "yellow"
"special" = "blue"
"ui.virtual.jump-label" = { fg = "#00dfff", modifiers = ["bold"] }

"markup.heading.marker" = "grey1"
"markup.heading.1" = { fg = "red", modifiers = ["bold"] }
"markup.heading.2" = { fg = "orange", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.6" = { fg = "purple", modifiers = ["bold"] }
"markup.list" = "red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "blue", underline = { style = "line" } }
"markup.link.label" = "orange"
"markup.link.text" = "purple"
"markup.quote" = "grey1"
"markup.raw.inline" = "green"
"markup.raw.block" = "aqua"

"diff.plus" = "green"
"diff.delta" = "blue"
"diff.minus" = "red"

"ui.background" = { bg = "bg0" }
"ui.background.separator" = "bg_visual"
"ui.cursor" = { fg = "bg1", bg = "grey2" }
"ui.cursor.normal" = { fg = "bg0", bg = "fg" }
"ui.cursor.insert" = { fg = "bg0", bg = "cursor_insert" }
"ui.cursor.select" = { fg = "bg0", bg = "cursor_select" }
"ui.cursor.primary.normal" = { fg = "bg1", bg = "fg", modifiers = ["dim"] }
"ui.cursor.primary.insert" = { fg = "bg1", bg = "cursor_insert", modifiers = ["dim"] }
"ui.cursor.primary.select" = { fg = "bg1", bg = "cursor_select", modifiers = ["dim"] }
"ui.cursor.match" = { fg = "orange", bg = "bg_yellow" }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg2" }
"ui.selection" = { bg = "bg3" }
"ui.linenr" = "grey0"
"ui.linenr.selected" = "grey2"
"ui.statusline" = { fg = "grey2", bg = "bg3" }
"ui.statusline.inactive" = { fg = "grey0", bg = "bg1" }
"ui.statusline.normal" = { fg = "bg0", bg = "statusline2", modifiers = [
  "bold",
] }
"ui.statusline.insert" = { fg = "bg0", bg = "statusline1", modifiers = [
  "bold",
] }
"ui.statusline.select" = { fg = "bg0", bg = "blue", modifiers = [
  "bold"
] }
"ui.bufferline" = { fg = "grey2", bg = "bg3" }
"ui.bufferline.active" = { fg = "bg0", bg = "statusline1", modifiers = [
  "bold",
] }
"ui.popup" = { fg = "grey2", bg = "bg2" }
"ui.window" = { fg = "bg4", bg = "bg_dim" }
"ui.help" = { fg = "fg", bg = "bg2" }
"ui.text" = "fg"
"ui.text.focus" = "fg"
"ui.menu" = { fg = "fg", bg = "bg3" }
"ui.menu.selected" = { fg = "bg0", bg = "green" }
"ui.virtual.ruler" = { bg = "bg1" }
"ui.virtual.whitespace" = { fg = "bg4" }
"ui.virtual.indent-guide" = { fg = "bg4" }
"ui.virtual.inlay-hint" = { fg = "grey0" }
"ui.virtual.wrap" = { fg = "grey0" }

"hint" = "green"
"info" = "blue"
"warning" = "yellow"
"error" = "red"

"diagnostic.hint" = { underline = { color = "green", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out", "dim"] }

[palette]
bg_dim = "#282425"
bg0 = "#2c2a2b"
bg1 = "#333031"
bg2 = "#3b3738"
bg3 = "#454142"
bg4 = "#4e4a4b"
bg5 = "#555151"
bg_visual = "#543a48"
bg_red = "#564044"
bg_green = "#494444"
bg_blue = "#43484a"
bg_yellow = "#4d4a48"
default = "#e8e0cf"

fg = "#d3c6aa" 
red = "#e67e80"
orange = "#e69875"
yellow = "#dbbc7f"
# green = "#a7c080"
# green = "#a4b38d"
green = "#b0af8b"
aqua = "#83c092"
blue = "#7fbbb3"
purple = "#d699b6"

grey0 = "#7a8478"
grey1 = "#859289"
grey2 = "#9da9a0"

statusline1 = "#b8d090"
statusline2 = "#FAA0A0"
statusline3 = "#f78e90"

cursor_normal = "#809164"
cursor_insert = "#af7070"
cursor_select = "#58827d"

constant = "#dca3a3"

